# Generated by Django 4.1.5 on 2023-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('membership', models.CharField(choices=[('S', 'Sports'), ('H', 'Health'), ('P', 'Politics'), ('E', 'Economics'), ('T', 'Technology')], max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
