# Generated by Django 4.1.5 on 2023-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='membership',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
